# Generated by Django 5.2.8 on 2025-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompInfo',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, max_length=300, null=True)),
                ('face_link', models.URLField(blank=True, max_length=300, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True)),
                ('web_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'comp_info',
            },
        ),
        migrations.CreateModel(
            name='CompName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'comp_name',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('report_pdf', models.FileField(upload_to='reports/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
