# Generated by Django 5.2.8 on 2025-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compname',
            name='ticker',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
