# Generated by Django 5.2.8 on 2025-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_compname_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_pdf',
        ),
        migrations.RemoveField(
            model_name='report',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
