# Generated by Django 5.2.8 on 2025-12-07 20:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_report_report_pdf_remove_report_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
        migrations.AddField(
            model_name='report',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
