# Generated by Django 5.2.8 on 2025-12-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_report_pdf_url_remove_report_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='thumbnail',
        ),
    ]
