# Generated by Django 5.2.8 on 2025-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_report_pdf_file_remove_report_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
