# Generated by Django 5.2.8 on 2025-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_report_pdf_url_report_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='compinfo',
            name='exchange',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='compinfo',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='exchange',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
